server:
  port: 8890
  tomcat:
    uri-encoding: UTF-8

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ok-stok-db-2?useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&jdbcCompliantTruncation=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
        username: root
        password: 
    http:
      encoding:
        enabled: true
        force: true
    jackson:
      serialization:
        INDENT_OUTPUT: true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            connection:
                characterEncoding: utf-8
                CharSet: utf-8
                useUnicode: true

    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 189397749547-575r3v6qlasaar4ccrosaglkbq7ll1eb.apps.googleusercontent.com
              clientSecret: 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
              redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 1527690294338498
              clientSecret: 89dc82d1652d3865dcd5c6a28b51531d
              redirect-uri : "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: d3e47fc2ddd966fa4352
              clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
              redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)      
    mail:
      host: smtp.gmail.com
      port: 587
      properties:
        mail:
          smtp:
            starttls:
              enable: true
              required: true
            auth: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
      username: faress.bnlk@gmail.com
      password: tcegqomosayrsqfa
    main:
      allow-bean-definition-overriding: true
app:
  auth:
    tokenSecret: OCICU99TWYGGPUVLE2WOEUZKANQCE6252UQZCB9A4GKIXUAENBNUUBQZPKH8LX7DOFT8BJZWTIZTDWLCZNNYVA
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:8100/oauth2/redirect
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
twilio:
  account_sid: AC018108b8c6ed7426b218de9ed3a54523
  auth_token: 1c8ec35392f34e48babae1053a6cd5e2
  trial_number: +12183967111
      
      
      